### ISSUE TITLE
Subject and BehaviorSubject and a bunch of other questions

### ISSUE THREAD

**Issue by AngelMunoz** [dbrattli/AsyncRx#5]
Hello there, I have a few questions
- Is there any particular reason on why was a tuple chosen as the output from a subject?

  with other reactiveX implementations (like the JS one) I would get a single object which I can emit new values and subscribe to

```fsharp
let s, o = AsyncRx.subject()

s.OnNextAsync(0)

o
|> AsyncRx.operator fn
|> AsyncRx.toObservable
|> Observable.add (fun f ->
    printfn $"Got {f}"
    if f = "q" then
        printfn "Exit"
        exit 0)
```

```js

let s = new Subject();

s.next(1);

s.pipe(operator(fn)).subscribe(do => theThing());
```

I found it a little bit odd coming from there it is not bad but it feels unfamiliar

- I was looking for the equivalent to BehaviorSubject but I found none
- How do you "observe" these async observables? (in the sample above I converted it to an observable then subscribed to that but I'm not sure if that's the right approach)

lastly...

- How do you start an AsyncSeq? the next fragment is what I came up with but I have no idea if that's actually a good way to start it

```fsharp
asyncSeq {
    while true do
        let! line = Console.In.ReadLineAsync() |> Async.AwaitTask
        do! s.OnNextAsync(line)
}
|> AsyncSeq.iterAsync Async.Ignore // not sure if this is okay
|> Async.RunSynchronously // don't let the console app to stop
```

For completenes sake I was playing with this kind of code:

```fsharp
open System
open FSharp.Control

let s, o = AsyncRx.subject ()

o
|> AsyncRx.tapOnNext (fun f -> printfn $"Tapped {f}")
|> AsyncRx.toObservable
|> Observable.add (fun f ->
    printfn $"Got {f}"

    if f = "q" then
        printfn "Exit"
        exit 0)


printfn "Entering asyncseq"

asyncSeq {
    while true do
        let! line = Console.In.ReadLineAsync() |> Async.AwaitTask
        do! s.OnNextAsync(line)
}
|> AsyncSeq.iterAsync Async.Ignore
|> Async.RunSynchronously
```

I love that this can be used in Fable and I might want experiment with it a little bit more kudos for your efforts with this library it look and feels really great!

**Comment by dbrattli** [comment]
Hi @AngelMunoz. Nice to see that you are playing with AsyncRx. It's a while since I wrote it, but I think the reason why subject returns two objects was an attempt to avoid the mutability. Subjects are the mutable objects of the stream world. You can set a value and then read it again afterwards, i.e BehaviourSubject. So instead AsyncRx returns two "entangled" objects, one observer and one observable. You can write to the observer and observe the observable, but they are not the same object. But then it's hard to make a BehaviourSubject. Let me think how we can make that ...

But the same way as e.g options and results can be unwrapped, we want to avoid the unwrap/wrap step with streams (if possible). Here is another subject-less way to do it:

```fs
#r "nuget: FSharp.Control.AsyncRx"
#r "nuget: FSharp.Control.AsyncRx.AsyncSeq"

open System
open System.Threading.Thread
open FSharp.Control

printfn "Entering asyncseq"

asyncSeq {
    while true do
        let! line = Console.In.ReadLineAsync() |> Async.AwaitTask
        yield line
}
|> AsyncRx.ofAsyncSeq
|> AsyncRx.tapOnNext (fun f -> printfn $"Tapped {f}")
|> AsyncRx.toObservable
|> Observable.add (fun f ->
    printfn $"Got {f}"

    if f = "q" then
        printfn "Exit"
        exit 0)

// To avoid exiting the program while the code above runs
for x in 1..100 do
    Sleep 1000
```

**Comment by AngelMunoz** [comment]
Yeah in this particular example asyncseq is more than enough, a more concise example than my original one would be this:

```fsharp
open System
open FSharp.Control

type Command =
    | Start
    | Stop
    | Pause
    | Restart
    | Unknown

[<RequireQualifiedAccess>]
module Command =

    let OfString (value: string) =
        match value.ToLowerInvariant() with
        | "start" -> Start
        | "stop" -> Stop
        | "pause" -> Pause
        | "restart" ->  Restart
        | _ -> Unknown

let parseLine line =
    // do some sort of parsing logic
    async {
        let cmd = Command.OfString line
        printfn $"Got %A{cmd}"
    }

asyncSeq {
    while true do
        let! line = Console.In.ReadLineAsync() |> Async.AwaitTask
        line
}
|> AsyncSeq.iterAsync parseLine
|> Async.RunSynchronously
```

I could use `AsyncSeq.map` and `AsyncSeq.iterAsync` to execute any kind of command that I can think of.

My questions were more about exploring how to work together with these in case it was needed and to ensure if that was relatively ok

I think as a consumer, it is simpler if I can handle both behaviors in a single object but it makes sense to have these objects separated if they are meant to perform each own thing

I think that example plus the docs make it very compelling to keep experimenting with it if I get stuck at some point I'll go back and annoy you a little bit 😄
